/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package calculator;

/**
 *
 * @author Sukrit
 */
public class CalculatorForm extends javax.swing.JFrame{

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zero = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        four = new javax.swing.JButton();
        three = new javax.swing.JButton();
        one = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        two = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        txtAreaResult = new javax.swing.JTextField();
        txtAreaCurrent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAreaAction = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(260, 254));

        zero.setText("0");
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                zeroMouseReleased(evt);
            }
        });

        nine.setText("9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nineMouseReleased(evt);
            }
        });

        five.setText("5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fiveMouseReleased(evt);
            }
        });

        six.setText("6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sixMouseReleased(evt);
            }
        });

        four.setText("4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fourMouseReleased(evt);
            }
        });

        three.setText("3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                threeMouseReleased(evt);
            }
        });

        one.setText("1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                oneMouseReleased(evt);
            }
        });
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        eight.setText("8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                eightMouseReleased(evt);
            }
        });
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        two.setText("2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                twoMouseReleased(evt);
            }
        });

        dot.setText(".");
        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dotMouseReleased(evt);
            }
        });
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        seven.setText("7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sevenMouseReleased(evt);
            }
        });

        minus.setText("_");
        minus.setMaximumSize(new java.awt.Dimension(41, 23));
        minus.setMinimumSize(new java.awt.Dimension(41, 23));
        minus.setPreferredSize(new java.awt.Dimension(41, 23));
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minusMouseReleased(evt);
            }
        });

        plus.setText("+");
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                plusMouseReleased(evt);
            }
        });

        multiply.setText("*");
        multiply.setMaximumSize(new java.awt.Dimension(41, 23));
        multiply.setMinimumSize(new java.awt.Dimension(41, 23));
        multiply.setPreferredSize(new java.awt.Dimension(41, 23));
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                multiplyMouseReleased(evt);
            }
        });

        divide.setText("/");
        divide.setMaximumSize(new java.awt.Dimension(41, 23));
        divide.setMinimumSize(new java.awt.Dimension(41, 23));
        divide.setPreferredSize(new java.awt.Dimension(41, 23));
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divideMouseReleased(evt);
            }
        });
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        equals.setText("=");
        equals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                equalsMouseReleased(evt);
            }
        });
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });

        txtAreaResult.setText(".........");
        txtAreaResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaResultActionPerformed(evt);
            }
        });

        txtAreaCurrent.setText(".........");

        jLabel1.setText("Result");

        jLabel2.setText("Current");

        jLabel3.setText("Action");

        txtAreaAction.setText(".........");

        clear.setText("CLEAR");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clearMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(four)
                            .addComponent(seven))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eight)
                            .addComponent(five))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(six)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(one)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(two)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(equals, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtAreaResult, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAreaCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(clear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtAreaAction, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAreaResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAreaCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAreaAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eight)
                            .addComponent(nine)
                            .addComponent(seven)
                            .addComponent(plus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(four)
                            .addComponent(five, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(six)
                        .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(three)
                    .addComponent(two)
                    .addComponent(one)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero)
                    .addComponent(dot)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dotActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divideActionPerformed

    private void zeroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroMouseReleased
        pressNumber(0);
        updateDisplays();
    }//GEN-LAST:event_zeroMouseReleased

    private void oneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseReleased
        pressNumber(1);
        
    }//GEN-LAST:event_oneMouseReleased

    private void dotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dotMouseReleased
        dot();
        updateDisplays();
    }//GEN-LAST:event_dotMouseReleased

    private void equalsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsMouseReleased
        performCalculation();
        current=0;
        currentDecimal=0;
        pendingOperation="none";
        updateDisplays();
        
    }//GEN-LAST:event_equalsMouseReleased

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalsActionPerformed

    private void plusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plusMouseReleased
        pendingOperation("+");
        //plus();
    }//GEN-LAST:event_plusMouseReleased

    private void txtAreaResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaResultActionPerformed

    private void threeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseReleased
        pressNumber(3);
        updateDisplays();
    }//GEN-LAST:event_threeMouseReleased

    private void twoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseReleased
        pressNumber(2);
        updateDisplays();
    }//GEN-LAST:event_twoMouseReleased

    private void fourMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseReleased
        pressNumber(4);
        updateDisplays();
    }//GEN-LAST:event_fourMouseReleased

    private void fiveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseReleased
        pressNumber(5);
        updateDisplays();
    }//GEN-LAST:event_fiveMouseReleased

    private void sixMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseReleased
        pressNumber(6);
        updateDisplays();
    }//GEN-LAST:event_sixMouseReleased

    private void sevenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseReleased
        pressNumber(7);
        updateDisplays();
    }//GEN-LAST:event_sevenMouseReleased

    private void eightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseReleased
        pressNumber(8);
        updateDisplays();
    }//GEN-LAST:event_eightMouseReleased

    private void nineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseReleased
        pressNumber(9);
        updateDisplays();
    }//GEN-LAST:event_nineMouseReleased

    private void minusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusMouseReleased
        pendingOperation("-");
        //minus();
        
    }//GEN-LAST:event_minusMouseReleased

    private void multiplyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyMouseReleased
        pendingOperation("*");
        //multiply();
        
    }//GEN-LAST:event_multiplyMouseReleased

    private void divideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseReleased
        pendingOperation("/");
        //divide();
        
    }//GEN-LAST:event_divideMouseReleased

    private void clearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseReleased
        clear();
        updateDisplays();
    }//GEN-LAST:event_clearMouseReleased

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JTextField txtAreaAction;
    private javax.swing.JTextField txtAreaCurrent;
    private javax.swing.JTextField txtAreaResult;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables



/////////////////////////////////////////////////////////////////////////////////////////////////
//*********************************************************************************************//


float result;
int current;
int currentDecimal;
int operationsCalled;

String pendingOperation = new String();
String insideDecimal = new String();    
    
    /**
     * Creates new form CalculatorForm
     */
public     CalculatorForm() {
        initComponents();
        result=0;
        current=0;
        currentDecimal=0;
        pendingOperation="none";    
        insideDecimal="none";
        operationsCalled=0;
    }
 
    

private void clear(){
        result=0;
        current=0;
        currentDecimal=0;
        pendingOperation="none";    
        insideDecimal="none";
        operationsCalled=0;
}

private double currentFull(){
    if(currentDecimal==0){
        return current;
    }else{
        return current + (currentDecimal  /   Math.pow(10, Math.floor( Math.log10(currentDecimal)+1   ) )    );
    }
}

private void pendingOperation(String pO){
    operationsCalled++;
    insideDecimal="none";        
    if(!"none".equals(pendingOperation)){ // Something like + - / * is present in pendingOperation
        performCalculation();
        current=0;
        currentDecimal=0;
        //moveCurrentToResult();
    
    }else if(operationsCalled==1 && "none".equals(pendingOperation) ){// For 1st Operations to move current UP
       moveCurrentToResult(); 
    }
    pendingOperation=pO;
    updateDisplays();
}


private void moveCurrentToResult(){
    result=(float) currentFull();
    current=0;
    currentDecimal=0;
}


private  void plus(){
    result=(float) (result+currentFull());
}


private  void minus(){
    result=(float) (result-currentFull());
}

private  void multiply(){
    result=(float) (result*currentFull());
}
 
private  void divide(){
    result=(float) (result/currentFull());
}

private float equals(){
    
    return result;
 }


private void dot(){
    insideDecimal="yes";
}


private void pressNumber(int num){
    if(!"yes".equals(insideDecimal)){
        current=current*10 + num;
    }else{
        currentDecimal=(currentDecimal*10)+num;
    }
    
    updateDisplays();
}


private float getResult(){
    return result;
}

private void updateDisplays(){
    String currentUD = Float.toString((float) currentFull());
    txtAreaCurrent.setText(currentUD);
    
    String resultUD = Float.toString((float) getResult());
    txtAreaResult.setText(resultUD);
    
     
    txtAreaAction.setText(pendingOperation);

}


private void performCalculation(){
    if("+".equals(pendingOperation)){
        plus();
    }else if("-".equals(pendingOperation)){
        minus();
    }else if("*".equals(pendingOperation)){
        multiply();
    }else if("/".equals(pendingOperation)){
        divide();
    }
}


//*********************************************************************************************//
/////////////////////////////////////////////////////////////////////////////////////////////////

}
